export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SET_SHOPPING_LIST = "SET_SHOPPING_LIST";
export const UPDATE_PRODUCT_QUANTITY = "UPDATE_PRODUCT_QUANTITY";
export const UPDATE_CART_COUNT = "UPDATE_CART_COUNT";
